export const MEXICAN_STATES_HSP: Record<string, number> = {
  "Aguascalientes": 5.5,
  "Baja California": 6.0,
  "Baja California Sur": 6.5,
  "Campeche": 5.0,
  "Chiapas": 4.8,
  "Chihuahua": 6.2,
  "Ciudad de Mexico": 5.2,
  "Coahuila": 6.0,
  "Colima": 5.5,
  "Durango": 5.8,
  "Guanajuato": 5.5,
  "Guerrero": 5.3,
  "Hidalgo": 5.0,
  "Jalisco": 5.5,
  "Estado de Mexico": 4.8,
  "Michoacan": 5.2,
  "Morelos": 5.5,
  "Nayarit": 5.5,
  "Nuevo Leon": 5.5,
  "Oaxaca": 5.5,
  "Puebla": 5.2,
  "Queretaro": 5.5,
  "Quintana Roo": 5.0,
  "San Luis Potosi": 5.8,
  "Sinaloa": 6.0,
  "Sonora": 6.5,
  "Tabasco": 4.5,
  "Tamaulipas": 5.5,
  "Tlaxcala": 5.0,
  "Veracruz": 4.8,
  "Yucatan": 5.2,
  "Zacatecas": 6.0
};
