// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sfv-layouts/FullscreenStep.tsx": () => import("../components/mockups/sfv-layouts/FullscreenStep.tsx"),
  "./components/mockups/sfv-layouts/HorizontalRail.tsx": () => import("../components/mockups/sfv-layouts/HorizontalRail.tsx"),
  "./components/mockups/sfv-layouts/RightContext.tsx": () => import("../components/mockups/sfv-layouts/RightContext.tsx")
};
